import colors from './colors';
const fontFamily = "'Encode Sans', sans-serif";
const typography = {
  body1: {
    color: colors.palette.black,
    fontFamily,
    fontSize: '1rem',
    fontWeight: 400,
    lineHeight: 1.5,
  },
  body2: {
    color: colors.palette.black,
    fontFamily,
    fontSize: '1rem',
    fontWeight: 400,
    lineHeight: 1.5,
  },
  button: {
    fontFamily,
    fontSize: '0.875rem',
    fontWeight: 400,
    lineHeight: 1.75,
  },
  cancel: {
    color: colors.palette.red,
    fontFamily,
    fontSize: '16px',
    fontWeight: 600,
    lineHeight: 1,
  },
  caption: {
    fontFamily,
    fontSize: '0.75rem',
    fontWeight: 400,
    lineHeight: 1.66,
  },
  fontFamily,
  fontSize: 16,
  fontWeightBold: 700,
  fontWeightLight: 300,
  fontWeightMedium: 500,
  fontWeightRegular: 400,
  h1: {
    color: colors.palette.black,
    fontFamily,
    fontSize: '48px',
    fontWeight: 700,
    lineHeight: '52px',
  },
  h2: {
    color: colors.palette.black,
    fontFamily,
    fontSize: '36px',
    fontWeight: 700,
    lineHeight: '40px',
  },
  h3: {
    color: colors.palette.black,
    fontFamily,
    fontSize: '24px',
    fontWeight: 700,
    lineHeight: '32px',
  },
  h4: {
    color: colors.palette.black,
    fontFamily,
    fontSize: '20px',
    fontWeight: 700,
    lineHeight: '28px',
  },
  h5: {
    color: colors.palette.black,
    fontFamily,
    fontSize: '18px',
    fontWeight: 700,
    lineHeight: '24px',
  },
  h6: {
    color: colors.palette.black,
    fontFamily,
    fontSize: '16px',
    fontWeight: 700,
    lineHeight: '24px',
  },
  htmlFontSize: 16,
  overline: {
    fontFamily,
    fontSize: '0.75rem',
    fontWeight: 400,
    lineHeight: 2.66,
    textTransform: 'uppercase',
  },
  subtitle1: {
    color: colors.palette.black,
    fontFamily,
    fontSize: '1rem',
    fontWeight: 400,
    lineHeight: 1.75,
  },
  subtitle2: {
    color: colors.palette.black,
    fontFamily,
    fontSize: '0.875rem',
    fontWeight: 500,
    lineHeight: 1.57,
  },
  subtitle3: {
    color: colors.palette.black,
    fontFamily,
    fontSize: '0.875rem',
    fontWeight: 400,
    lineHeight: 1.57,
  },
  success: {
    color: colors.palette.green,
    fontFamily,
    fontSize: '16px',
    fontWeight: 600,
    lineHeight: 1,
  },
};
export default typography;
